# This file lints the code, builds a package and then deploys it.
# For the deployment, $BINTRAY_USER, $BINTRAY_KEY and $GH_TOKEN environment
# variables need to be set.
language: php

matrix:
    include:
        - php: 7.3
        - php: 7.2
        - php: 7.1
        - php: 7.0
          env: CS_FIXER=true LINT_JS=true
        - php: 5.6
          env: DEPLOY=true
    fast_finish: true
env:
    - COMPOSER_NO_INTERACTION=1

addons:
    apt:
        packages:
            - jq

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - nvm install 12
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi
    - composer self-update

install:
    - phpenv config-rm xdebug.ini
    - npm run install-dependencies

script:
    - if [ "$LINT_JS" = true ]; then npm run lint:client; fi
    - npm run lint:server
    - if [ "$CS_FIXER" = true ]; then npm run cs:server; fi
    - npm run test:server

before_deploy:
    - git config --global user.email 'Travis CI'
    - git config --global user.name 'builds@travis-ci.org'
    - source utils/package.sh
    - source utils/bintray.sh

deploy:
    - provider: bintray
      file: utils/bintray.json
      user: $BINTRAY_USER
      key: $BINTRAY_KEY
      skip_cleanup: true
      on:
          condition: $DEPLOY = true
    - provider: releases
      api_key: $GH_TOKEN
      file: $SELFOSS_ZIPBALL
      skip_cleanup: true
      on:
          tags: true
          condition: $DEPLOY = true
