title = "selfoss"
description = "Open source web based RSS reader and multi-source mashup aggregator."
base_url = "https://selfoss.aditu.de"

compile_sass = true

[extra]
author = "Tobias Zeising"
author_address = "tobias.zeising@aditu.de"
current_stable_version = "2.19"
